FROM ubuntu:14.04
MAINTAINER openthings@163.com

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
	curl \
        git \
        wget \
        libatlas-base-dev \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libhdf5-serial-dev \
        libleveldb-dev \
        liblmdb-dev \
        libopencv-dev \
        libprotobuf-dev \
        libsnappy-dev \
        protobuf-compiler \
        python-pip \
	python-wheel \
        python-dev \
        python-numpy \
        python-scipy \
	software-properties-common 


# =========Install JDK8.====================================================

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

RUN 	echo ">>>>>> Install JDK8,PWD: "$PWD &&\
	echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections &&\
  	add-apt-repository -y ppa:webupd8team/java &&\
  	apt-get update &&\
  	apt-get install -y oracle-java8-installer 


# =========Install bazel.===================================================

RUN 	echo ">>>>>> Install bazel,PWD: "$PWD &&\
	echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | \
		tee /etc/apt/sources.list.d/bazel.list &&\
	curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add - &&\
	apt-get update && \
	apt-get install -y bazel &&\
	echo ">>>>>> Success install bazel,PWD: "$PWD

#apt-get upgrade bazel
#wget https://github.com/bazelbuild/bazel/releases/tag/0.4.3 -O bazel


