FROM openthings/bazel
MAINTAINER openthings@163.com

# =========Build tensorflow.================================================

ENV TENSORFLOW_ROOT=/opt/tensorflow
WORKDIR $TENSORFLOW_ROOT

# =========Build all-in docker =============================================
# FIXME: clone a specific git tag and use ARG instead of ENV once DockerHub supports this.
#ENV CLONE_TAG=master
#RUN git clone --progress -b ${CLONE_TAG} --depth 1 https://github.com/tensorflow/tensorflow.git . 


# =========Build in docker =================================================
ADD ./tensorflow /opt/tensorflow
RUN 	echo ">>>>>> Build tensorflow,PWD: "$PWD &&\
	bazel build -c opt //tensorflow/tools/pip_package:build_pip_package


